let { MessageEmbed } = require('discord.js')

module.exports = {
    nombre: 'teclas',
    alias: [],
    descripcion: "Enseña las teclas del servidor",
    run: async(client, message, args) => {
        
        message.delete()
        const embed = new MessageEmbed()
        .setTitle("💻 CONTROLES ADICIONALES 💻")
        .setAuthor('FreshLifeRP', 'https://cdn.discordapp.com/attachments/866584743494942793/892978969580830790/sin_gorra_512x512_movimiento.gif?width=641&height=641')
        .setThumbnail("https://cdn.discordapp.com/attachments/866584743494942793/892978969580830790/sin_gorra_512x512_movimiento.gif?width=641&height=641")
        .addField("¿Para que sirve esta sección?", "Aqui podrás encontrar los controles adicionales añadidos dentro del servidor de roleplay, ya sea para cerrar tu coche como para hacer animaciones integradas mediante un shortcut físico.")
        .addField("═══════۩⭐۩═══════", "\u200B\n")
        .addfield('\u200B', "\u200B")
        .addField("[F1] [📱] = Abrir el teléfono movil", "En el teléfono móvil podrás encontrar aplicaciones bancarias, para mensajería etc...")
        .addfield('\u200B', "\u200B")
        .addField("[F2] [📦] = Abrir el inventario", "Para ver que llevas encima... No te excedas en peso, se considera PG. ")
        .addfield('\u200B', "\u200B")
        .addField("[F3] [🕺] = Menú de animaciones", "¡Dale realismo visual a tu experiencia de rol! Las animaciones visuales no se representan con un /me")
        .addfield('\u200B', "\u200B")
        .addField("[F5] [🔪] = Menú para mafias", "Es un menú para integrantes de  organizaciones ilegales.")
        .addfield('\u200B', "\u200B")
        .addField("[F6] [👮] = Menú para policías", "Es el menú para complementar la labor policial")
        .addfield('\u200B', "\u200B")
        .addField("[F8] [🖥️] = Abrir la consola de FiveM", "Consola de comandos global de FiveM")
        .addfield('\u200B', "\u200B")
        .addField("[F9] [👕] = Menú radial de ropa", "Acceder al menu radial de acceso rapido de ropa.")
        .addfield('\u200B', "\u200B")
        .addField("[F10] [💳] = Información personal", "Tu DNI, licencias de armas, de conducir.")
        .addfield('\u200B', "\u200B")
        .addField("[ALT] [📻] = Animación de radio", "El PJ hará la animación de hablar por radio (Obligatorio para comunicarse remotamente)")
        .addfield('\u200B', "\u200B")
        .addField("[SUPR] [📑] = Lista de jugadores", "Lista de personas conectadas y trabajadores, su uso IC se considera MG")
        .addfield('\u200B', "\u200B")
        .addField("[X] [🙌] = Animación levantar manos", "¡Arriba las manos!")
        .addfield('\u200B', "\u200B")
        .addField("[K] [👕] = Apariencia, ropa", "Menú de ropa de acceso rápido.")
        .addfield('\u200B', "\u200B")
        .addField("[L] [🚗] = Abrir el maletero de un vehículo", "Para acceder al maletero de tu coche.")
        .addfield('\u200B', "\u200B")
        .addField("[M] [🚗] = Cinturón de seguridad", "Ponte el cinturón de seguridad en el coche, no queremos accidentes")
        .addfield('\u200B', "\u200B")
        .addField("[H] [🚗] = Luces del vehículo", "Pon las luces de cruce en la ciudad o cambia a las de carretera.")
        .addfield('\u200B', "\u200B")
        .addField("[U] [🚗] = Cerrar/Abrir vehículo", "Usa las llaves del coche para cerrar o abrir tu vehículo.")
        .addfield('\u200B', "\u200B")
        .addField("[F] [🚗] = Entrar/Salir vehículo", "Para montarse en vehículos de todo tipo.")
        .addfield('\u200B', "\u200B")
        .addField("[H] [🙆] = Cachear a otro PJ", "Debes portar un arma.")
        .addfield('\u200B', "\u200B")
        .addField("[Q] [🌳] = Usar una cobertura", "Nativo de GTAV, no presente en muchos servidores, usalo correctamente.")
        .addfield('\u200B', "\u200B")
        .addField("[T] [📜] = Canal de texto", "Canal para comandos: /me /do /ooc /report /anon /twt /suelo")
        .addfield('\u200B', "\u200B")
        .addField("[P] [🗺️] = Abrir el mapa", "El abuso de su información IG se considera MG.")
        .setColor("GREEN")
        .setImage("https://cdn.discordapp.com/attachments/866584743494942793/892978969580830790/sin_gorra_512x512_movimiento.gif")
        message.channel.send(embed)
    }
}